"""
Django settings for happy_birthday project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialise environment variables


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d3-wz38)^3ftu851=nlle1wvf0o%+9+ob=*u(!(zu@&iw#2dp+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'questionnaire',
    'django_inlinecss',
]
SITE_ID = 1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    
]

CORS_ALLOWED_ORIGINS = [
    
    "http://localhost:3000",
]

ROOT_URLCONF = 'happy_birthday.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates').replace('\\','/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'happy_birthday.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
RUN_ON_HEROKU =os.environ.get('RUN_ON_HEROKU')
print(RUN_ON_HEROKU)
if RUN_ON_HEROKU == '0':
    sql_db_conf = {
        
            'ENGINE':'django.db.backends.mysql',
            'NAME': 'questionnaire',
            'USER': {'NAME':'root',
                    'PASSWORD': 'nick9176'},
            'HOST': '127.0.0.1',
            'PORT': 3306,
        
    }
if RUN_ON_HEROKU == '1':
    sql_db_conf = {
    'ENGINE':'django.db.backends.postgresql_psycopg2',
    'HOST': 'ec2-54-157-113-118.compute-1.amazonaws.com',
    'PORT': 5432,
    'NAME': 'd69c76efs9dhme',
    'USER': {
        'NAME': 'jophmskxhahmej',
        'PASSWORD': 'c191e15462921b6220b0fa1ae4aa4335c876c87a5f0744beffedf3ca00ac0cea'
    }
}
DATABASES = {
    'default': {
        'ENGINE': sql_db_conf['ENGINE'], 
        'NAME': sql_db_conf['NAME'],
        'USER': sql_db_conf['USER']['NAME'],
        'PASSWORD': sql_db_conf['USER']['PASSWORD'],
        'HOST': sql_db_conf['HOST'],
        'PORT': sql_db_conf['PORT'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = 'questionnaire/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'questionnaire/static') ]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  #SMTP伺服器
EMAIL_PORT = 587  #TLS通訊埠號
EMAIL_USE_TLS = True  #開啟TLS(傳輸層安全性)
EMAIL_HOST_USER = 'chivestsai@gmail.com'  #寄件者電子郵件
EMAIL_HOST_PASSWORD = 'iwlmwjhqrbcqtnwr'  #Gmail應用程式的密碼