# Generated by Django 3.2.4 on 2023-01-10 16:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='問題題目')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '問卷問題表',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(max_length=200, null=True)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('prize', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1)])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=32, verbose_name='選項名稱')),
                ('option_type', models.CharField(max_length=32, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='questionnaire.questions', verbose_name='所在的問題')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(blank=True, null=True, verbose_name='數字答案')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本答案')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_option', to='questionnaire.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='questionnaire.questions', verbose_name='所屬問題')),
            ],
            options={
                'verbose_name_plural': '問卷回答表',
            },
        ),
    ]
