# Generated by Django 2.2.26 on 2022-01-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='問卷名')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '問卷表',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='問題題目')),
                ('questionnaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire', verbose_name='所屬問卷')),
            ],
            options={
                'verbose_name_plural': '問卷問題表',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=32, verbose_name='選項名稱')),
                ('score', models.IntegerField(verbose_name='選項對應的分值')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questions', verbose_name='所在的問題')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(blank=True, null=True, verbose_name='數字答案')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本答案')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Option')),
                ('queston', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questions', verbose_name='所屬問題')),
            ],
            options={
                'verbose_name_plural': '問卷回答表',
            },
        ),
    ]
