# Generated by Django 3.2.4 on 2023-01-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
