# Generated by Django 2.2.26 on 2022-01-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='questions',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
