# Generated by Django 2.2.26 on 2022-01-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20220118_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='score',
        ),
    ]
