# Generated by Django 3.2.4 on 2023-01-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
