# Generated by Django 2.2.26 on 2022-01-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20220118_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='queston',
            new_name='question',
        ),
    ]
