# Generated by Django 3.2.4 on 2023-01-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_answer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_verified',
        ),
    ]
