# Generated by Django 2.2.26 on 2022-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20220118_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
