# Generated by Django 2.2.26 on 2022-02-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_option_option_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='questionnaire',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
