# Generated by Django 3.2.4 on 2023-01-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_remove_questions_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='val',
        ),
    ]
