# Generated by Django 3.2.4 on 2023-01-12 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_remove_answer_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='input_costs',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
