# Generated by Django 3.2.4 on 2023-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_userprofile_input_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='input_costs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
